apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
  namespace: app
spec:
  selector:
    app: spring-boot-app
  ports:
    - name: http
      port: 80
      targetPort: 8081
  type: LoadBalancer
